# Generated by Django 6.0.2 on 2026-02-11 15:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='about/')),
                ('about_text', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('github_link', models.URLField()),
                ('telegram_link', models.URLField()),
                ('instagram_link', models.URLField()),
            ],
        ),
    ]
